name: Local to Main - Analyze & Format Check

on:
  push:
    branches:
      - main

jobs:
  analyze_and_format:
    name: Analyze & Check Prettier Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint Analysis
        run: npm run lint || echo "⚠️ ESLint found issues."

      - name: Check Prettier Formatting
        run: npm run prettier:check || echo "⚠️ Prettier format issues found."
